### ISSUE TITLE
ImportError: No module named handshakesettings

### ISSUE THREAD

**Issue by voxsim** [freshplanet/AppEngine-SocketPool#1]
I tried to integrate this library in my appengine, but i received this error:

No module named handshakesettings
Traceback (most recent call last):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/handlers/SendQuestionsHandler.py", line 37, in get
    collapse_key='questions'
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/utils.py", line 81, in sendNotification
    return sendIOSNotification(registrationId, payload)
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/utils.py", line 112, in sendIOSNotification
    from apn import APNSender, getNotifRequest
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/apn.py", line 23, in <module>
    from socketPool import PooledConnection
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/socketPool.py", line 23, in <module>
    from tlslite import TLSConnection, X509, X509CertChain, parsePEMKey
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/tlslite/**init**.py", line 27, in <module>
    from tlslite.api import *
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380686684213612159/tlslite/api.py", line 8, in <module>
    from .handshakesettings import HandshakeSettings
ImportError: No module named handshakesettings

Do you have any suggestions?

Thanks,
Simon

**Comment by voxsim** [comment]
I resolved changing the name from handshakesettings to hssettings.

**Comment by AlexisH** [comment]
hum ok. does not make much sense to me though.
Have you included the tlslite library from this repository into your project or taken from elsewhere?

**Comment by voxsim** [comment]
Yes, but I have this error and another one: Could you describe what kind of pem do you want? I tried with the pem downloaded from apple, but the code return me 'Incorrect padding'.

**Comment by AlexisH** [comment]
the pem file content should looks like this:

```
Bag Attributes
    friendlyName: Apple Development IOS Push Services: com.example.MyApp
    localKeyID: ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
subject=/UID= com.example.MyApp/CN=Apple Development IOS Push Services:  com.example.MyApp/OU=MTC64E52Y4/C=US
issuer=/C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
-----BEGIN CERTIFICATE-----
******* 
    (base 64 data)
******
-----END CERTIFICATE-----
Bag Attributes
    friendlyName: FirstName LastName
    localKeyID: ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
Key Attributes: <No Attributes>
-----BEGIN RSA PRIVATE KEY-----
******* 
    (base 64 data)
******
-----END RSA PRIVATE KEY-----
```

**Comment by voxsim** [comment]
Perfect, thanks, i resolved! 

One last thing, i called the code with something similar to this snippet:

from apn import APNSender, getNotifRequest

certFileName = 'appymeteo.pem'
hostName = 'gateway.sandbox.push.apple.com'
requests = [getNotifRequest(token_hex, 'hello')]

data = APNSender(certFileName, hostName, requests).run()
logging.error("sendIOSNotification data: %s"%data)

But now I received '[Errno 32] Broken pipe' because maybe i don't close correctly the underlying used socket. Do you have an example on how to use it?
I just copied the code from the comment, tomorrow I will read tlslite btw.

**Comment by AlexisH** [comment]
Your snippet looks good.

You should not close the underlying socket AppEngine will close it for you
after 2 minutes of inactivity (and we'll re-use it if we have to send
another notification before this happens).

I don't remember exactly what triggers this error, except when trying to
send though a socket that's been closed already but the lib should handle
that.
Make sure you run this from AppEngine and not the devserver.
Make sure certificate stage (development or production) matches the host
and that the token is from the right app on the same stage.

Alexis

**Comment by voxsim** [comment]
hmm nothing, after two minutes i still have the same error and to be real sure I reduced _findconnection that return every time a new connection and now I received this error:

[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/handlers/SendQuestionsHandler.py", line 37, in get
    collapse_key='questions'
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/utils.py", line 81, in sendNotification
    return sendIOSNotification(registrationId, payload)
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/utils.py", line 118, in sendIOSNotification
    data = APNSender(certFileName, hostName, requests).run()
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/socketPool.py", line 79, in run
    return self.runAsync().get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 325, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 371, in _help_tasklet_along
    value = gen.send(val)
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/socketPool.py", line 88, in runAsync
    connection = yield self._findConnection()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1003, in tasklet_wrapper
    result = func(_args, *_kwds)
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/socketPool.py", line 145, in _findConnection
    raise ndb.Return(self.getNewConnection())
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/socketPool.py", line 116, in getNewConnection
    connection.handshakeClientCert(chain, key)
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 299, in handshakeClientCert
    for result in handshaker:
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 314, in _handshakeClientAsync
    for result in self._handshakeWrapperAsync(handshaker, checker):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 1646, in _handshakeWrapperAsync
    for result in handshaker:
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 463, in _handshakeClientAsyncHelper
    cipherSuite, settings.cipherImplementations):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 867, in _clientFinished
    for result in self._sendFinished(masterSecret):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsconnection.py", line 1561, in _sendFinished
    for result in self._sendMsg(ChangeCipherSpec()):
  File "/base/data/home/apps/s~happymeteo/backend-push:2014-12-10.380687649379366939/tlslite/tlsrecordlayer.py", line 590, in _sendMsg
    bytesSent = self.sock.send(s) #Might raise socket.error
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 940, in send
    return self.sendto(data, flags, None)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 1000, in sendto
    raise _SystemExceptionFromAppError(e)

and it seems something related to App Engine

**Comment by AlexisH** [comment]
is you app billing enabled?
Sockets are only available for such apps

Alexis

**Comment by voxsim** [comment]
Yes I enabled yesterday, the first thing I will do it will be trying tlslite on my machine, if everything works I will really start to worry :p
